spring:
  profiles:
    active: local-postgres
---
spring:
  config:
    activate:
      on-profile: local-postgres
  datasource:
    url: jdbc:postgresql://localhost:15432/testadmin
    username: testadmin
    password: 1111
    hikari:
      auto-commit: true
  jpa:
    hibernate:
      ddl-auto: 'create-drop'
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

